name: project
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  location: ^5.0.0
  cupertino_icons: ^1.0.2
  intl: ^0.17.0  
  geocoding: ^2.0.1
  provider: ^5.0.0
  weather_icons: ^3.0.0
  weather_animation: ^0.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - images/sunny_sunflowers.jpg
    - images/cloudy_sunflowers.jpg
    - images/rainy_sunflowers.jpg
    - images/sunny_cloudy_sunflowers.jpg
    - gifs/sun.gif
    - gifs/cloudy.gif
    - gifs/rain.gif
  uses-material-design: true

